version: 2
updates:
# Oppdaterer Terraform-moduler
  - package-ecosystem: "terraform"
    directory: "/modules/azurefirewall"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/azurefirewallpolicy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/azurefirewallrulecolgrp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/bastion"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/publicip"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/recoveryservicesvault"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/resourcegroups"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/routetables"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/vm-linux"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/vm-windows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/vnet-peering"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/vnet"
    schedule:
      interval: "weekly"

